### ISSUE TITLE
Can't build in Xcode 5.0 - build error.

### ISSUE THREAD

**Issue by robertturrall** [lorenbrichter/SimFinger#31]
I'm getting a build error when trying to run from the current Master branch:

FakeFingerAppDelegate.m:65:32: Use of undeclared identifier 'kAXTrustedCheckOptionPrompt'

Followed by a warning on the next line:

FakeFingerAppDelegate.m:66:30: Implicit declaration of function 'AXIsProcessTrustedWithOptions' is invalid in C99

Am I missing a build option or something?
